title: Takashi Shibuya
description: Research Scientist at Sony
url: "https://yahshibu.github.io"
author:
  name: Takashi Shibuya
  affiliation: Sony
  email: Takashi.Tak.Shibuya@sony.com
  github: takashi-shibuya
  scholar: XCRO260AAAAJ  # Google Scholar ID
  orcid: 0000-0002-4277-0164  # ORCID
  semantic_scholar: 47720660  # Semantic Scholar ID
  linkedin: takashi-shibuya-7596a439
markdown: kramdown
