organizer:
  - role: "Organizer"
    venue: "ECCV 2026"
    title: "Generative AI for Audio-Visual Content Creation"
    short: "Gen4AVC"
    url: "https://gen4avc.github.io/eccv2026/"
  - role: "Organizer"
    venue: "NeurIPS 2025"
    title: "Generative and Protective AI for Content Creation"
    short: "GenProCC"
    url: "https://genprocc.github.io/"
  - role: "Organizer"
    venue: "ICCV 2025"
    title: "AI for Content Generation, Quality Enhancement and Streaming"
    short: "AIGENS"
    url: "https://ai4streaming-workshop.github.io/2025/index.html"
  - role: "Organizer"
    venue: "ICCV 2025"
    title: "Generative AI for Audio-Visual Content Creation"
    short: "Gen4AVC"
    url: "https://gen4avc.github.io/iccv2025/"

